### ISSUE TITLE
Requirements (master issue)

### ISSUE THREAD

**Issue by svametcalf** [svametcalf/jbar#1]
This is a master issue to keep track of requirements for this app. 
# Overall purpose

This app is supposed to be a compendium of accident reports for accidents that happen in Juneau. This app is built with the goal of public education and transferring knowledge about mistakes and lessons learned from accidents in the backcountry.  

## Existing examples 

 - [Accidents in North American Mountaineering](http://publications.americanalpineclub.org/about_accidents)

## Basic use cases

 - Public should be able to read accident reports for accidents that happen in the backcountry around Juneau 
 - Users should be able to create and edit their own accident reports, with input from content administrators / reviewers
 - Public should be able to see a map of where reports are written about 

## Technical Specifications

This app should be as simple to build and run as possible. Here is a list of the anticipated technologies: 
- Docker / docker-compose, for dev env and running in production
- Some sort of document based NoSQL DB, such as CouchDB
- EmberJS for frontend
- Markdown for rich text markup

## Things that need to happen now: 

- [ ] Develop technical requirements and specs (#2)
- [ ] Setup development environment (#3)
- [ ] Develop data model (ie list of questions that will be asked when users submit reports, authentication schemes, how to deal with images/ videos, etc)  (#4)
- [ ] Implement data model in backend (#5)
- [ ] Implement front end.   (#6)
